name = "ToyProject"
uuid = "f3fb54a7-ccbe-499a-b107-e14070cf16d6"
version = "1.0.0-DEV"
authors = ["ch"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.12.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
